image: confido/docker-buildx

stages:
  - build
  - test
  - push
  - clean

variables:
  DOCKER_ARGS: "core 5.6 7.0 7.1 7.2 7.3 7.4 8.0 8.1 8.2 8.3"
  DOCKER_ARCH: "linux/arm/v7,linux/arm64/v8,linux/amd64"
  DOCKER_TEMP: "build-${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_IID}"
  DOCKER_BASE: "${DOCKER_ACC}/${DOCKER_PKG}"


docker build:
  stage: build
  only:
    - develop
    - master
  script:
    - chmod +x ./.gitlab/build.sh && ./.gitlab/build.sh

docker test:
  stage: test
  only:
    - develop
    - master
  script:
    - chmod +x ./.gitlab/test.sh && ./.gitlab/test.sh

docker push:
  stage: push
  only:
    - master
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - chmod +x ./.gitlab/push.sh && ./.gitlab/push.sh

docker clean:
  stage: clean
  only:
    - develop
    - master
  script:
    - chmod +x ./.gitlab/clean.sh && ./.gitlab/clean.sh