image: confido/buildx-qemu:latest

services:
  - docker:dind

before_script:
  - docker info

variables:
  DOCKER_UNIQ: "build-${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_IID}"
  DOCKER_NAME: "${DOCKER_ACC}/${DOCKER_PKG}"
  DOCKER_ARCH: "linux/amd64,linux/arm64"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - init
  - test
  - prepare
  - build

default:
  tags:
    - docker
    - linux
    - arch-amd64

.tpl-base:
  before_script:
    # Vars
    - DOCKER_PHP=$([[ $BUILD_VERSION == php* ]] && echo ${BUILD_VERSION:3:3} || echo "false")
    - DOCKER_TAG=$BUILD_VERSION$([[ $BUILD_NPM == "true" ]] && echo "-npm" || echo "")
    - DOCKER_CACHE=$CI_REGISTRY_IMAGE:buildcache-${CI_PIPELINE_ID}-core$([[ $BUILD_NPM == "true" ]] && echo "-npm" || echo "")
    # Init
    - echo "Building $DOCKER_ARCH image for \"$DOCKER_TAG\" from \"$CI_COMMIT_BRANCH\" branch:" \
      && echo " - Container PHP is ${DOCKER_PHP:-false}" \
      && echo " - Container NPM is $BUILD_NPM" \
      && echo " - Cache is $DOCKER_CACHE" \
      && echo " - Runner ID is $CI_RUNNER_ID" \
      && echo " - Runner Arch is $CI_RUNNER_EXECUTABLE_ARCH"
    # Registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
    # Buildx Initing
    - docker context create "context-$CI_JOB_ID"
    - docker buildx create --name "builder-$CI_JOB_ID" --use "context-$CI_JOB_ID"
    - docker buildx inspect --bootstrap
  after_script:
    # Cleaning
    - docker buildx rm "builder-$CI_JOB_ID" || true
    - docker context rm "context-$CI_JOB_ID" || true

.tpl-test:
  extends:
    - .tpl-base
  script:
    # Build
    - if [ $BUILD_VERSION = "core" ]; then docker buildx build --no-cache --cache-to type=registry,ref=$DOCKER_CACHE,mode=max --build-arg NPM_PACKAGE=$BUILD_NPM --platform $CI_RUNNER_EXECUTABLE_ARCH --tag $DOCKER_UNIQ:$DOCKER_TAG . --load; fi
    - if [ $BUILD_VERSION != "core" ]; then docker buildx build --cache-from type=registry,ref=$DOCKER_CACHE --build-arg PHP_VERSION=$DOCKER_PHP --build-arg NPM_PACKAGE=$BUILD_NPM --platform $CI_RUNNER_EXECUTABLE_ARCH --tag $DOCKER_UNIQ:$DOCKER_TAG . --load; fi
    # Test
    - docker run --name $DOCKER_UNIQ-$DOCKER_TAG $DOCKER_UNIQ:$DOCKER_TAG >/dev/null 2>&1 &
    - echo "docker run --name $DOCKER_UNIQ-$DOCKER_TAG $DOCKER_UNIQ:$DOCKER_TAG >/dev/null 2>&1 &"
    - echo "Waiting for container to be up and running (timeout 10 seconds)..." && sleep 10
    - docker exec $DOCKER_UNIQ-$DOCKER_TAG /bin/bash /health.sh
    - DOCKER_CODE=$?
    - docker stop $DOCKER_UNIQ-$DOCKER_TAG || true
    - docker rm $DOCKER_UNIQ-$DOCKER_TAG || true
    - docker rmi $DOCKER_UNIQ:$DOCKER_TAG || true
    - if test $DOCKER_CODE -ne 0; then echo " - failed" && exit 1; fi

.tpl-build:
  extends:
    - .tpl-base
  script:
    # Build
    - if [ $BUILD_VERSION = "core" ]; then docker buildx build --cache-from type=registry,ref=$DOCKER_CACHE --cache-to type=registry,ref=$DOCKER_CACHE,mode=max --build-arg NPM_PACKAGE=$BUILD_NPM --platform $DOCKER_ARCH --tag $DOCKER_NAME:$DOCKER_TAG . --push; fi
    - if [ $BUILD_VERSION != "core" ]; then docker buildx build --cache-from type=registry,ref=$DOCKER_CACHE --build-arg PHP_VERSION=$DOCKER_PHP --build-arg NPM_PACKAGE=$BUILD_NPM --platform $DOCKER_ARCH --tag $DOCKER_NAME:$DOCKER_TAG . --push; fi
  dependencies:
    - dummy-ssl

test_core:
  stage: test
  extends:
    - .tpl-test
  parallel:
    matrix:
      - BUILD_VERSION: [ 'core' ]
        BUILD_NPM: [ 'true', 'false' ]

initing:
  stage: init
  script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

test_php:
  stage: test
  extends:
    - .tpl-test
  needs:
    - job: test_core
  parallel:
    matrix:
      - BUILD_VERSION: [ 'php5.6', 'php7.0', 'php7.1', 'php7.2', 'php7.3', 'php7.4', 'php8.0', 'php8.1', 'php8.2', 'php8.3', 'php8.4' ]
        BUILD_NPM: [ 'true', 'false' ]

dummy-ssl:
  stage: prepare
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - openssl dhparam -out ./ssl/dhparam.pem 4096
    - openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout ./ssl/default.key -out ./ssl/default.crt -subj '/C=NO/ST=Null/L=Null/O=Null/OU=Null/CN=Null'
  artifacts:
    name: $DOCKER_UNIQ
    expire_in: 1 hour
    paths:
      - ssl/

build_core:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  extends:
    - .tpl-build
  parallel:
    matrix:
      - BUILD_VERSION: [ 'core' ]
        BUILD_NPM: [ 'true', 'false' ]

build_php:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  extends:
    - .tpl-build
  needs:
    - job: build_core
  parallel:
    matrix:
      - BUILD_VERSION: [ 'php5.6', 'php7.0', 'php7.1', 'php7.2', 'php7.3', 'php7.4', 'php8.0', 'php8.1', 'php8.2', 'php8.3', 'php8.4' ]
        BUILD_NPM: [ 'true', 'false' ]
