image: confido/buildx-qemu:latest

services:
  - docker:dind

before_script:
  - docker info

variables:
  DOCKER_UNIQ: "build-${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_IID}"
  DOCKER_NAME: "${DOCKER_ACC}/${DOCKER_PKG}"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - test_core
  - test_php
  - prepare
  - release
  - build_core
  - build_php

.tpl-test:
  before_script:
    # Args
    - DOCKER_PHP=$([[ $BUILD_VERSION == php* ]] && echo ${BUILD_VERSION:3:3} || echo "")
    - DOCKER_TAG=$BUILD_VERSION$([[ $BUILD_NPM == "true" ]] && echo "-npm" || echo "")
  script:
    # Build
    - echo "Building \"$DOCKER_TAG\" from \"$CI_COMMIT_BRANCH\" branch (PHP is ${DOCKER_PHP:-false}, NPM is $BUILD_NPM)"
    - if [ $BUILD_VERSION = "core" ]; then docker build -t $DOCKER_UNIQ:$DOCKER_TAG --no-cache --build-arg NPM_PACKAGE=$BUILD_NPM .; fi
    - if [ $BUILD_VERSION != "core" ]; then docker build -t $DOCKER_UNIQ:$DOCKER_TAG --cache-from $DOCKER_UNIQ:core --build-arg PHP_VERSION=$DOCKER_PHP --build-arg NPM_PACKAGE=$BUILD_NPM .; fi
    # Test
    - echo "Testing \"$DOCKER_TAG\" from \"$CI_COMMIT_BRANCH\" branch (PHP is ${DOCKER_PHP:-false}, NPM is $BUILD_NPM)"
    - docker run --name $DOCKER_UNIQ-$DOCKER_TAG $DOCKER_UNIQ:$DOCKER_TAG >/dev/null 2>&1 &
    - echo "Waiting for container to be up and running (timeout 10 seconds)..." && sleep 10
    - docker exec $DOCKER_UNIQ-$DOCKER_TAG /bin/bash /health.sh
    - DOCKER_CODE=$?
    - if test $DOCKER_CODE -ne 0; then echo " - failed" && exit 1; fi

.tpl-build:
  before_script:
    # Args
    - DOCKER_PHP=$([[ $BUILD_VERSION == php* ]] && echo ${BUILD_VERSION:3:3} || echo "")
    - DOCKER_TAG=$BUILD_VERSION$([[ $BUILD_NPM == "true" ]] && echo "-npm" || echo "")
    - BUILDER_NAME="builder-$CI_JOB_ID"
    - CONTEXT_NAME="context-$CI_JOB_ID"
  script:
    # Buildx
    - if [ ! -f /proc/sys/fs/binfmt_misc/qemu-aarch64 ]; then docker run --rm --privileged multiarch/qemu-user-static --reset -p yes; fi
    - docker context create "$CONTEXT_NAME"
    - docker buildx create --name "$BUILDER_NAME" --use "$CONTEXT_NAME"
    - docker buildx inspect --bootstrap
    # Registry
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
    # Build part
    - echo "Final multiarch images for \"$DOCKER_TAG\" from \"$CI_COMMIT_BRANCH\" branch (PHP is ${DOCKER_PHP:-false}, NPM is $BUILD_NPM)"
    - if [ $BUILD_VERSION = "core" ]; then docker buildx build --platform $BUILD_ARCH --tag $DOCKER_NAME:$DOCKER_TAG --build-arg NPM_PACKAGE=$BUILD_NPM --push .; fi
    - if [ $BUILD_VERSION != "core" ]; then docker buildx build --platform $BUILD_ARCH --tag $DOCKER_NAME:$DOCKER_TAG --build-arg PHP_VERSION=$DOCKER_PHP --build-arg NPM_PACKAGE=$BUILD_NPM --push .; fi
    # Cleaning
    - docker buildx rm "$BUILDER_NAME"
    - docker context rm "$CONTEXT_NAME"
  dependencies:
    - dhparam

test_core:
  extends: .tpl-test
  stage: test_core
  parallel:
    matrix:
      - BUILD_VERSION: ['core']
        BUILD_NPM: ['true', 'false']

test_php:
  extends: .tpl-test
  stage: test_php
  parallel:
    matrix:
      - BUILD_VERSION: ['php5.6', 'php7.0', 'php7.1', 'php7.2', 'php7.3', 'php7.4', 'php8.0', 'php8.1', 'php8.2', 'php8.3', 'php8.4']
        BUILD_NPM: ['false']

dhparam:
  stage: prepare
  only:
    - master
  script:
    - openssl dhparam -out ./ssl/dhparam.pem 4096
    - openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout ./ssl/default.key -out ./ssl/default.crt -subj '/C=NO/ST=Null/L=Null/O=Null/OU=Null/CN=Null'
  artifacts:
    name: $DOCKER_UNIQ
    expire_in: 1 hour
    paths:
      - ssl/

buildx_core:
  extends: .tpl-build
  stage: build_core
  only:
    - master
  parallel:
    matrix:
      - BUILD_ARCH: ['linux/amd64', 'linux/arm64']
        BUILD_VERSION: ['core']
        BUILD_NPM: ['true', 'false']

buildx_php:
  extends: .tpl-build
  stage: build_php
  only:
    - master
  parallel:
    matrix:
      - BUILD_ARCH: ['linux/amd64', 'linux/arm64']
        BUILD_VERSION: ['php5.6', 'php7.0', 'php7.1', 'php7.2', 'php7.3', 'php7.4', 'php8.0', 'php8.1', 'php8.2', 'php8.3', 'php8.4']
        BUILD_NPM: ['true', 'false']
