[unix_http_server]
file=/run/supervisor.sock
username = schyachlo
password = popyachsa
chmod=0700

[supervisord]
user=root
nodaemon=true
pidfile=/run/supervisord.pid
loglevel=warn
logfile=/dev/null
logfile_maxbytes=0

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[eventlistener:exit_on_fatal]
command=bash -c "printf 'READY\n' && while read line; do kill -SIGQUIT $PPID; done < /dev/stdin"
events=PROCESS_STATE_FATAL

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
username = schyachlo
password = popyachsa

[program:nginx]
command=nginx -c /etc/nginx/nginx.conf
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startsecs=3
startretries=3

[program:logs]
command=tail -f /tmp/docker.log
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
startsecs=3
startretries=3